-- MySQL Script generated by MySQL Workbench
-- Fri Feb  5 15:27:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clickCreate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clickCreate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clickCreate` DEFAULT CHARACTER SET utf8 ;
USE `clickCreate` ;

-- -----------------------------------------------------
-- Table `clickCreate`.`cc_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(350) NOT NULL,
  `pwd` VARCHAR(255) NOT NULL,
  `country` CHAR(2) NOT NULL,
  `status` TINYINT(4) NOT NULL,
  `isDeleted` TINYINT(1) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NULL,
  `id_role` INT NOT NULL,
  `address` VARCHAR(350) NULL,
  `city` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(10) NULL,
  PRIMARY KEY (`id`, `id_role`),
  INDEX `fk_User_role1_idx` (`id_role` ASC),
  CONSTRAINT `fk_User_role1`
    FOREIGN KEY (`id_role`)
    REFERENCES `clickCreate`.`cc_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `address` VARCHAR(255) NOT NULL,
  `city` VARCHAR(150) NOT NULL,
  `zipCode` VARCHAR(5) NOT NULL,
  `phoneNumber` VARCHAR(10) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day` VARCHAR(8) NULL,
  `openHour` VARCHAR(2) NULL,
  `closeHour` VARCHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `description` LONGTEXT NULL,
  `picPath` VARCHAR(350) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `status` TINYINT(5) NOT NULL,
  `Category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Category_id`),
  INDEX `fk_Products_Category1_idx` (`Category_id` ASC),
  CONSTRAINT `fk_Products_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `clickCreate`.`cc_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(5) NULL,
  `color` VARCHAR(45) NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_productPic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_productPic` (
  `id` INT NOT NULL,
  `path` VARCHAR(350) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_shop_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_shop_schedule` (
  `id_schedule` INT NOT NULL,
  `id_shop` INT NOT NULL,
  PRIMARY KEY (`id_schedule`, `id_shop`),
  INDEX `fk_shop_schedule_Shop1_idx` (`id_shop` ASC),
  CONSTRAINT `fk_shop_schedule_Schedule1`
    FOREIGN KEY (`id_schedule`)
    REFERENCES `clickCreate`.`cc_schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shop_schedule_Shop1`
    FOREIGN KEY (`id_shop`)
    REFERENCES `clickCreate`.`cc_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_quantityShop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_quantityShop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NULL,
  `Shop_id` INT NOT NULL,
  `Model_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Shop_id`, `Model_id`),
  INDEX `fk_QuantityProduct_Shop1_idx` (`Shop_id` ASC),
  INDEX `fk_QuantityProduct_Model1_idx` (`Model_id` ASC),
  CONSTRAINT `fk_QuantityProduct_Shop1`
    FOREIGN KEY (`Shop_id`)
    REFERENCES `clickCreate`.`cc_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QuantityProduct_Model1`
    FOREIGN KEY (`Model_id`)
    REFERENCES `clickCreate`.`cc_model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_model_productPic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_model_productPic` (
  `Model_id` INT NOT NULL,
  `ProductPic_id` INT NOT NULL,
  PRIMARY KEY (`Model_id`, `ProductPic_id`),
  INDEX `fk_Model_productPic_ProductPic1_idx` (`ProductPic_id` ASC),
  CONSTRAINT `fk_Model_productPic_Model1`
    FOREIGN KEY (`Model_id`)
    REFERENCES `clickCreate`.`cc_model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Model_productPic_ProductPic1`
    FOREIGN KEY (`ProductPic_id`)
    REFERENCES `clickCreate`.`cc_productPic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_promotion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` TINYINT(5) NULL,
  `type` TINYINT(2) NULL,
  `valueType` FLOAT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `expiryDate` DATE NOT NULL,
  `quantity` INT NOT NULL,
  `minimumAmount` FLOAT NULL,
  `minimumQuantity` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_promotion_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_promotion_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Products_id` INT NOT NULL,
  `Promotion_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Products_id`, `Promotion_id`),
  INDEX `fk_Promotion_product_Products1_idx` (`Products_id` ASC),
  INDEX `fk_Promotion_product_Promotion1_idx` (`Promotion_id` ASC),
  CONSTRAINT `fk_Promotion_product_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `clickCreate`.`cc_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Promotion_product_Promotion1`
    FOREIGN KEY (`Promotion_id`)
    REFERENCES `clickCreate`.`cc_promotion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_promotion_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_promotion_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Promotion_id` INT NOT NULL,
  `Category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Promotion_id`, `Category_id`),
  INDEX `fk_Promotion_category_Promotion1_idx` (`Promotion_id` ASC),
  INDEX `fk_Promotion_category_Category1_idx` (`Category_id` ASC),
  CONSTRAINT `fk_Promotion_category_Promotion1`
    FOREIGN KEY (`Promotion_id`)
    REFERENCES `clickCreate`.`cc_promotion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Promotion_category_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `clickCreate`.`cc_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_orders` (
  `id` INT NOT NULL,
  `Products_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `CreatedAt` TIMESTAMP NULL,
  `status` TINYINT(5) NULL,
  PRIMARY KEY (`id`, `Products_id`, `User_id`),
  INDEX `fk_Orders_Products1_idx` (`Products_id` ASC),
  INDEX `fk_Orders_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Orders_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `clickCreate`.`cc_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `clickCreate`.`cc_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commentary` LONGTEXT NULL,
  `mark` FLOAT NULL,
  `Products_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Products_id`, `User_id`),
  INDEX `fk_Review_Products1_idx` (`Products_id` ASC),
  INDEX `fk_Review_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Review_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `clickCreate`.`cc_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `clickCreate`.`cc_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_pages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `slug` VARCHAR(255) NULL,
  `path` VARCHAR(255) NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_Pages_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Pages_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `clickCreate`.`cc_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickCreate`.`cc_products_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickCreate`.`cc_products_model` (
  `Products_id` INT NOT NULL,
  `Model_id` INT NOT NULL,
  PRIMARY KEY (`Products_id`, `Model_id`),
  INDEX `fk_table1_Model1_idx` (`Model_id` ASC),
  CONSTRAINT `fk_table1_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `clickCreate`.`cc_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_Model1`
    FOREIGN KEY (`Model_id`)
    REFERENCES `clickCreate`.`cc_model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
